### ISSUE TITLE
Non ordered lines

### ISSUE THREAD

**Issue by Lukeg32-intel** [Echo545/Threshing-Floor#1]
yo is me, making issues on your github
if i reverse the chaffed.txt file you should make it still figure it out the message since you are using a serial number that is correlated to that bits position in the sequence.   
you could also remove the clear text serial number, and just have the winnower program guess which serial number it should be, obviously this would make the program take longer but would be slightly more efficient for bandwidth

**Comment by Echo545** [comment]
Latest version of `winnow.py` now handles inputs with the order shuffled. It also handles missing lines by guessing the missing values.
